### ISSUE TITLE
Need horizontal Header titles for all day event with dynamic height

### ISSUE THREAD

**Issue by AbhijeetRukmangad** [Quivr/Android-Week-View#32]
Hello,

I need to have all day event titles displayed horizontally one below each other. Also the number of all day events can be more than 5 so the header height should be dynamically adjusted.

Can someone please guide/direct me on how can I implement these changes.

Thanks in anticipation of your response.

**Comment by jhoobergs** [comment]
Hi @AbhijeetRukmangad 

You mean that 2 all day events are placed on top of each other instead of side to side ?
What do you exactly mean with dynamically adjusting header height ?

You have to change things at https://github.com/Quivr/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekView.java#L686 , here https://github.com/Quivr/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekView.java#L929 and some other places you will find by searching for allDay in WeekView.java

**Comment by AbhijeetRukmangad** [comment]
Thanks a lot @jhoobergs. your tip did help. I missed updates in getHeaderHeight().. 

I wanted to show vertical list of allday events rather than horizontal. I did achieve this.

Now I am stuck with event loading part. I load events from server so I get them asynchronously. But weekview expects event to be loaded asynchronously through onMonthChange(..) method.

How can I make it asynchronous where in I will just supply events as I get and weekview should be able to grab them.

**Comment by jhoobergs** [comment]
You can start by looking at https://github.com/Quivr/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/AsynchronousActivity.java#L29

Or change you api to return the events per month.
